### ISSUE TITLE
driver/spi_slave.h not found

### ISSUE THREAD

**Issue by 7be** [iPAS/esp32-slave-spi#3]
compiling the test.ino it throws the error

`\Arduino\libraries\SlaveSPI/SlaveSPI.h:6:30: fatal error: driver/spi_slave.h: No such file or directory`
which makes sense as i do not have the file.
the file is not supported in this git
the readme.md does not state anything about it

**Comment by sabas1080** [comment]
Only move "SlaveSPI.h" to the folder of the sketch
